config/routes.rb
Cheetahquotes::Application.routes.draw do
  resources :company_laptops

  resources :graphic_memories

  resources :memories

  resources :cores

  resources :hard_drives

  resources :companies

  resources :laptops

end

app/models/company_laptop.rb
class CompanyLaptop < ActiveRecord::Base
  attr_accessible :cantidad, :company_id, :laptop_id
end

app/controllers/company_laptop_controller.rb
class CompanyLaptopController < ApplicationController
end

app/controllers/company_laptops_controller.rb
class CompanyLaptopsController < ApplicationController
  # GET /company_laptops
  # GET /company_laptops.json
  def index
    @company_laptops = CompanyLaptop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @company_laptops }
    end
  end

  # GET /company_laptops/1
  # GET /company_laptops/1.json
  def show
    @company_laptop = CompanyLaptop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @company_laptop }
    end
  end

  # GET /company_laptops/new
  # GET /company_laptops/new.json
  def new
    @company_laptop = CompanyLaptop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @company_laptop }
    end
  end

  # GET /company_laptops/1/edit
  def edit
    @company_laptop = CompanyLaptop.find(params[:id])
  end

  # POST /company_laptops
  # POST /company_laptops.json
  def create
    @company_laptop = CompanyLaptop.new(params[:company_laptop])

    respond_to do |format|
      if @company_laptop.save
        format.html { redirect_to @company_laptop, :notice => 'Company laptop was successfully created.' }
        format.json { render :json => @company_laptop, :status => :created, :location => @company_laptop }
      else
        format.html { render :action => "new" }
        format.json { render :json => @company_laptop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /company_laptops/1
  # PUT /company_laptops/1.json
  def update
    @company_laptop = CompanyLaptop.find(params[:id])

    respond_to do |format|
      if @company_laptop.update_attributes(params[:company_laptop])
        format.html { redirect_to @company_laptop, :notice => 'Company laptop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @company_laptop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /company_laptops/1
  # DELETE /company_laptops/1.json
  def destroy
    @company_laptop = CompanyLaptop.find(params[:id])
    @company_laptop.destroy

    respond_to do |format|
      format.html { redirect_to company_laptops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/company_laptop_helper.rb
module CompanyLaptopHelper
end

app/helpers/company_laptops_helper.rb
module CompanyLaptopsHelper
end

app/views/company_laptops/_form.html.erb
<%= form_for(@company_laptop) do |f| %>
  <% if @company_laptop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company_laptop.errors.count, "error") %> prohibited this company_laptop from being saved:</h2>

      <ul>
      <% @company_laptop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.number_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :laptop_id %><br />
    <%= f.number_field :laptop_id %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br />
    <%= f.number_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/company_laptops/edit.html.erb
<h1>Editing company_laptop</h1>

<%= render 'form' %>

<%= link_to 'Show', @company_laptop %> |
<%= link_to 'Back', company_laptops_path %>

app/views/company_laptops/index.html.erb
<h1>Listing company_laptops</h1>

<table>
  <tr>
    <th>Company</th>
    <th>Laptop</th>
    <th>Cantidad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @company_laptops.each do |company_laptop| %>
  <tr>
    <td><%= company_laptop.company_id %></td>
    <td><%= company_laptop.laptop_id %></td>
    <td><%= company_laptop.cantidad %></td>
    <td><%= link_to 'Show', company_laptop %></td>
    <td><%= link_to 'Edit', edit_company_laptop_path(company_laptop) %></td>
    <td><%= link_to 'Destroy', company_laptop, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company laptop', new_company_laptop_path %>

app/views/company_laptops/new.html.erb
<h1>New company_laptop</h1>

<%= render 'form' %>

<%= link_to 'Back', company_laptops_path %>

app/views/company_laptops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @company_laptop.company_id %>
</p>

<p>
  <b>Laptop:</b>
  <%= @company_laptop.laptop_id %>
</p>

<p>
  <b>Cantidad:</b>
  <%= @company_laptop.cantidad %>
</p>


<%= link_to 'Edit', edit_company_laptop_path(@company_laptop) %> |
<%= link_to 'Back', company_laptops_path %>