config/routes.rb
Cheetahquotes::Application.routes.draw do
  resources :company_laptops

  resources :graphic_memories

  resources :memories

  resources :cores

  resources :hard_drives

  resources :companies

  resources :laptops

end

app/models/memory.rb
class Memory < ActiveRecord::Base
  attr_accessible :ddr, :frecuencia, :marca, :tamaño
  has_and_belongs_to_many :laptops
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  # GET /memories
  # GET /memories.json
  def index
    @memories = Memory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @memories }
    end
  end

  # GET /memories/1
  # GET /memories/1.json
  def show
    @memory = Memory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @memory }
    end
  end

  # GET /memories/new
  # GET /memories/new.json
  def new
    @memory = Memory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @memory }
    end
  end

  # GET /memories/1/edit
  def edit
    @memory = Memory.find(params[:id])
  end

  # POST /memories
  # POST /memories.json
  def create
    @memory = Memory.new(params[:memory])

    respond_to do |format|
      if @memory.save
        format.html { redirect_to @memory, :notice => 'Memory was successfully created.' }
        format.json { render :json => @memory, :status => :created, :location => @memory }
      else
        format.html { render :action => "new" }
        format.json { render :json => @memory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /memories/1
  # PUT /memories/1.json
  def update
    @memory = Memory.find(params[:id])

    respond_to do |format|
      if @memory.update_attributes(params[:memory])
        format.html { redirect_to @memory, :notice => 'Memory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @memory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /memories/1
  # DELETE /memories/1.json
  def destroy
    @memory = Memory.find(params[:id])
    @memory.destroy

    respond_to do |format|
      format.html { redirect_to memories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/views/memories/_form.html.erb
<%= form_for(@memory) do |f| %>
  <% if @memory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memory.errors.count, "error") %> prohibited this memory from being saved:</h2>

      <ul>
      <% @memory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marca %><br />
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :frecuencia %><br />
    <%= f.number_field :frecuencia %>
  </div>
  <div class="field">
    <%= f.label :tamaño %><br />
    <%= f.number_field :tamaño %>
  </div>
  <div class="field">
    <%= f.label :ddr %><br />
    <%= f.number_field :ddr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memories/edit.html.erb
<h1>Editing memory</h1>

<%= render 'form' %>

<%= link_to 'Show', @memory %> |
<%= link_to 'Back', memories_path %>

app/views/memories/index.html.erb
<h1>Listing memories</h1>

<table>
  <tr>
    <th>Marca</th>
    <th>Frecuencia</th>
    <th>Tamaño</th>
    <th>Ddr</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memories.each do |memory| %>
  <tr>
    <td><%= memory.marca %></td>
    <td><%= memory.frecuencia %></td>
    <td><%= memory.tamaño %></td>
    <td><%= memory.ddr %></td>
    <td><%= link_to 'Show', memory %></td>
    <td><%= link_to 'Edit', edit_memory_path(memory) %></td>
    <td><%= link_to 'Destroy', memory, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Memory', new_memory_path %>

app/views/memories/new.html.erb
<h1>New memory</h1>

<%= render 'form' %>

<%= link_to 'Back', memories_path %>

app/views/memories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Marca:</b>
  <%= @memory.marca %>
</p>

<p>
  <b>Frecuencia:</b>
  <%= @memory.frecuencia %>
</p>

<p>
  <b>Tamaño:</b>
  <%= @memory.tamaño %>
</p>

<p>
  <b>Ddr:</b>
  <%= @memory.ddr %>
</p>


<%= link_to 'Edit', edit_memory_path(@memory) %> |
<%= link_to 'Back', memories_path %>