config/routes.rb
Cheetahquotes::Application.routes.draw do
  resources :company_laptops

  resources :graphic_memories

  resources :memories

  resources :cores

  resources :hard_drives

  resources :companies

  resources :laptops

end

app/models/laptop.rb
class Laptop < ActiveRecord::Base
  attr_accessible :marca, :modelo, :precio
  has_and_belongs_to_many :companies
  belongs_to :hard_drives
  belongs_to :cores
  has_and_belongs_to_many :memories
  belongs_to :graphic_memories
end

app/controllers/laptop_controller.rb
class LaptopController < ApplicationController
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  # GET /laptops
  # GET /laptops.json
  def index
    @laptops = Laptop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @laptops }
    end
  end

  # GET /laptops/1
  # GET /laptops/1.json
  def show
    @laptop = Laptop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @laptop }
    end
  end

  # GET /laptops/new
  # GET /laptops/new.json
  def new
    @laptop = Laptop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @laptop }
    end
  end

  # GET /laptops/1/edit
  def edit
    @laptop = Laptop.find(params[:id])
  end

  # POST /laptops
  # POST /laptops.json
  def create
    @laptop = Laptop.new(params[:laptop])

    respond_to do |format|
      if @laptop.save
        format.html { redirect_to @laptop, :notice => 'Laptop was successfully created.' }
        format.json { render :json => @laptop, :status => :created, :location => @laptop }
      else
        format.html { render :action => "new" }
        format.json { render :json => @laptop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /laptops/1
  # PUT /laptops/1.json
  def update
    @laptop = Laptop.find(params[:id])

    respond_to do |format|
      if @laptop.update_attributes(params[:laptop])
        format.html { redirect_to @laptop, :notice => 'Laptop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @laptop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /laptops/1
  # DELETE /laptops/1.json
  def destroy
    @laptop = Laptop.find(params[:id])
    @laptop.destroy

    respond_to do |format|
      format.html { redirect_to laptops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/laptop_helper.rb
module LaptopHelper
end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/views/laptops/_form.html.erb
<%= form_for(@laptop) do |f| %>
  <% if @laptop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@laptop.errors.count, "error") %> prohibited this laptop from being saved:</h2>

      <ul>
      <% @laptop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :precio %><br />
    <%= f.number_field :precio %>
  </div>
  <div class="field">
    <%= f.label :modelo %><br />
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :marca %><br />
    <%= f.text_field :marca %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/laptops/edit.html.erb
<h1>Editing laptop</h1>

<%= render 'form' %>

<%= link_to 'Show', @laptop %> |
<%= link_to 'Back', laptops_path %>

app/views/laptops/index.html.erb
<h1>Listing laptops</h1>

<table>
  <tr>
    <th>Precio</th>
    <th>Modelo</th>
    <th>Marca</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @laptops.each do |laptop| %>
  <tr>
    <td><%= laptop.precio %></td>
    <td><%= laptop.modelo %></td>
    <td><%= laptop.marca %></td>
    <td><%= link_to 'Show', laptop %></td>
    <td><%= link_to 'Edit', edit_laptop_path(laptop) %></td>
    <td><%= link_to 'Destroy', laptop, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Laptop', new_laptop_path %>

app/views/laptops/new.html.erb
<h1>New laptop</h1>

<%= render 'form' %>

<%= link_to 'Back', laptops_path %>

app/views/laptops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Precio:</b>
  <%= @laptop.precio %>
</p>

<p>
  <b>Modelo:</b>
  <%= @laptop.modelo %>
</p>

<p>
  <b>Marca:</b>
  <%= @laptop.marca %>
</p>


<%= link_to 'Edit', edit_laptop_path(@laptop) %> |
<%= link_to 'Back', laptops_path %>